before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  ldflags:
    - -s -w -X github.com/k1LoW/dio.version={{.Version}} -X github.com/k1LoW/dio.commit={{.FullCommit}} -X github.com/k1LoW/dio.date={{.Date}} -X github.com/k1LoW/dio/version.Version={{.Version}}
archives:
-
  id: dio-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: dio
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/dio
  description: 'Read/Write command using Direct I/O.'
  install: bin.install 'dio'
